### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Meatball2008** [jiangdequan/vscode-java-saber#13]
- Issue Type: `Bug`
- Extension Name: `vscode-java-saber`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jiangdequan** [comment]
Please provide more information about the problem.
