### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marisilvia** [jiangdequan/vscode-java-saber#14]
- Issue Type: `Performance` - Extension Name: `vscode-java-saber` - Extension Version: `0.1.1` - OS Version: `Windows_NT ia32 10.0.19041` - VSCode version: `1.41.1` :warning: Make sure to **attach** this file from your *home*-directory: :warning:`C:\Users\user\YouMayCallMeV.vscode-java-saber-unresponsive.cpuprofile.txt` Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jiangdequan** [comment]
I didn't meet the problem you described.
I need more details about your operations.
And can you provide the file you mentioned above?

**Comment by jiangdequan** [comment]
Maybe it caused by other plugins
