### ISSUE TITLE
Can't create java new package in command palette

### ISSUE THREAD

**Issue by Racso-3141** [jiangdequan/vscode-java-saber#18]
![WechatIMG1](https://user-images.githubusercontent.com/61854273/88821883-c45f6400-d1f5-11ea-832c-8815dd8b255c.jpeg)
I just install 'Java IDE' in my vscode. I want to create a package in my directory. In command palette, I type 'java new', there is no option 'java new package' asn shown above. Please help me. Thank U.

**Comment by jiangdequan** [comment]
"Java: New Package" is not supported in command palette yet.
You can use it by "Right click on the package -> New -> Package"
