### ISSUE TITLE
Running in debug mode fails if Java app not already compiled

### ISSUE THREAD

**Issue by rajinder-yadav** [jiangdequan/vscode-java-saber#23]
Issue Type: <b>Bug</b>

When running a Spring Boot Java app, if the application is not first compiled, then running in debug mode will fail with an error, "Could not find or load main class ..."

You can run maven clean first, then try to run in debug mode to see this failure. This happens with a Spring Boot app, but may also happen with a plain Java app (have't checked).

IDE should be smart enough to compile the app before starting debug mode.

Debug run error output
```pre
cd /home/yadav/dev/java/spring-boot/jpa-pg-student-demo2 ; /usr/bin/env /home/yadav/.sdkman/candidates/java/11.0.11.j9-adpt/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:42191 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=33847 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dspring.application.admin.enabled=true -Dspring.jmx.enabled=true -Dfile.encoding=UTF-8 @/tmp/cp_bl46fnr8tea12tujxkvyje5rm.argfile com.example.jpastudentdemo.JpaStudentDemoApplication 
Error: Could not find or load main class com.example.jpastudentdemo.JpaStudentDemoApplication
Caused by: java.lang.ClassNotFoundException: com.example.jpastudentdemo.JpaStudentDemoApplication
```

Extension version: 0.1.2
VS Code version: Code - Insiders 1.57.0-insider (82767cc1d7bf8cdea0f2897276d5d15aee91f3d9, 2021-05-17T05:13:35.197Z)
OS version: Linux x64 5.12.9-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3887)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.29GB (2.08GB free)|
|Process Argv|. --crash-reporter-id 7994aa03-2cc6-40be-91f0-a86a9abf4373|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/default|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30319630
vscgsv2:30305091
vscorehov:30301224
vscod805cf:30301675
vscextlang:30310088
vsccppwtct:30312693

```

</details>

**Comment by jiangdequan** [comment]
This extension does not have the function you described.
It is some other extension's log.
