### ISSUE TITLE
Failed to create a new file, cannot get the effective active text editor or selected file!

### ISSUE THREAD

**Issue by Retoxic** [jiangdequan/vscode-java-saber#4]
Can't create any kind of java files (class, enum, interface etc.). Every time when I try I receive the message in right down corner of VSC "Failed to create a new file, cannot get the effective active text editor or selected file!".

Version: 1.28.1
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:09:20.566Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Elementary OS 0.4.1 Loki
4.15.0-36-generic #39~16.04.1-Ubuntu

**Comment by jiangdequan** [comment]
If you create a new file in command way, you must keep a active tab in the editor.
If not, I need some more details.

**Comment by Retoxic** [comment]
What kind of information do you need? I have no any info in the VSC log files.

**Comment by jiangdequan** [comment]
I have built a ubuntu environment with vbox and reproduced this problem.
