### ISSUE TITLE
创建java文件，为什么默认包名是package io.github.jiangdequan;  

### ISSUE THREAD

**Issue by litaiqing** [jiangdequan/vscode-java-saber#7]
package io.github.jiangdequan;

public class TestController {
    
}

在哪里可以修改？不可以设置为当前path吗

**Comment by jiangdequan** [comment]
通过右键方式创建，会自动去获取包路径的；如果没有获取到，则会是一个默认值“io.github.jiangdequan”

If the extension can not get the path of package, "io.github.jiangdequan" is the default value for that.

**Comment by litaiqing** [comment]
如何修改默认值呢？

**Comment by jiangdequan** [comment]
目前，该值是定义在代码中的

Currently, the value is defined in the code.

**Comment by jiangdequan** [comment]
你是怎么操作的呢？怎么会获取不到包路径呢？

**Comment by litaiqing** [comment]
OK，我只是右键单击新建。可能与我的环境配置有关吧

**Comment by quinnInChina** [comment]
如果获取不到，可以从哪里自定义设置呢

**Comment by jiangdequan** [comment]
目前，使用官方的插件已经支持创建类等功能了，可以尝试使用官方的
