### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by coincashbank** [jiangdequan/vscode-java-saber#9]
- Issue Type: `Bug`
- Extension Name: `vscode-java-saber`
- Extension Version: `0.1.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jiangdequan** [comment]
Please provide more information about the problem.

**Comment by jiangdequan** [comment]
From the information provided above, do not know what the problem is.Please provide the operations to reproduce the problem.
